import type { CommerceProduct } from "@/types/product";

export const mockProducts: CommerceProduct[] = [
  {
    id: "mock-1",
    defaultVariantId: "mock-variant-1",
    slug: "kokocang-x",
    name: "口口舱X",
    status: "published",
    brand: "享要",
    series: "口口舱",
    thumbnail: undefined,
    images: [],
    price: 427,
    compareAtPrice: 553,
    currency: "CNY",
    inventoryQuantity: 99,
    allowBackorder: false,
    material: "液态硅胶 + POM + ABS",
    waterproof: "IPX6",
    runtimeMinutes: 45,
    chargeMinutes: 150,
    weightGrams: 336,
    sizeText: "82.8*81.5*161.1mm",
    stimulationType: ["licking", "suction", "clitoral"],
    appControl: true,
    remoteControl: true,
    wearable: false,
    heating: false,
    coupleFriendly: true,
    beginnerLevel: 3,
    intensityLevel: 4,
    noiseLevel: 3,
    discreetLevel: 2,
    tags: ["hero"],
    collections: ["clitoral-licking", "app-controlled"],
  },
  {
    id: "mock-2",
    defaultVariantId: "mock-variant-2",
    slug: "haili",
    name: "海狸",
    status: "published",
    brand: "享要",
    series: "穿戴",
    thumbnail: undefined,
    images: [],
    price: 229,
    compareAtPrice: 259,
    currency: "CNY",
    inventoryQuantity: 99,
    allowBackorder: false,
    material: "硅胶 + ABS",
    waterproof: "IPX7",
    runtimeMinutes: 50,
    chargeMinutes: 70,
    weightGrams: 61,
    sizeText: "85.5*43*99mm",
    stimulationType: ["dual", "clitoral", "insertable"],
    appControl: true,
    remoteControl: true,
    wearable: true,
    heating: false,
    coupleFriendly: true,
    beginnerLevel: 4,
    intensityLevel: 3,
    noiseLevel: 4,
    discreetLevel: 5,
    tags: ["wearable"],
    collections: ["wearable", "discreet-play", "app-controlled", "couples"],
  },
  {
    id: "mock-3",
    defaultVariantId: "mock-variant-3",
    slug: "handou",
    name: "含豆",
    status: "published",
    brand: "享要",
    series: "含豆",
    thumbnail: undefined,
    images: [],
    price: 327,
    compareAtPrice: 427,
    currency: "CNY",
    inventoryQuantity: 99,
    allowBackorder: false,
    material: "ABS + 硅胶 + 液态硅胶",
    waterproof: "IPX6",
    runtimeMinutes: 90,
    chargeMinutes: 60,
    weightGrams: 206,
    sizeText: "90*28mm",
    stimulationType: ["dual", "suction", "insertable", "clitoral"],
    appControl: true,
    remoteControl: true,
    wearable: false,
    heating: false,
    coupleFriendly: false,
    beginnerLevel: 3,
    intensityLevel: 4,
    noiseLevel: 4,
    discreetLevel: 3,
    tags: ["dual"],
    collections: ["dual-stimulation", "app-controlled"],
  },
];
