import type { SupportedLocaleKey } from "@/lib/site/locale-routing";

export function getHeaderNavLabel(href: string, fallback: string, localeKey: SupportedLocaleKey) {
  if (localeKey === "zh") return fallback;

  const labels: Record<string, string> = {
    "/shop": "Shop",
    "/guides": "Guides",
    "/faq": "FAQ",
    "/app-control": "App Control",
    "/bundles": "Bundles",
    "/privacy": "Privacy",
    "/returns": "Returns",
    "/shipping": "Shipping",
    "/contact": "Contact",
  };

  return labels[href] || fallback;
}

export function getFooterNavLabel(href: string, fallback: string, localeKey: SupportedLocaleKey) {
  return getHeaderNavLabel(href, fallback, localeKey);
}

export function getLocalizedCopy(localeKey: SupportedLocaleKey) {
  if (localeKey === "en") {
    return {
      header: {
        shop: "Shop",
        cart: "Cart",
      },
      newsletter: {
        title: "Subscribe",
        description: "Get new releases, guides, and shipping updates without high-frequency noise.",
        submitIdle: "Subscribe",
        submitPending: "Submitting...",
        emptyEmail: "Please enter your email address.",
        submitError: "Subscription failed. Please try again later.",
        submitSuccess: (brandName: string) => `Subscribed to ${brandName} updates.`,
      },
      home: {
        heroTitle: "A more guided, easier-to-buy intimate essentials shop.",
        heroDescription:
          "From first-time picks and scenario-based filtering to checkout and post-purchase support, this storefront is built to turn curiosity into confident purchases.",
        primaryCta: "Enter shop",
        secondaryCta: "Take the quiz first",
        stats: ["Products live", "Standard shipping SLA", "Shopping & support"],
        whyTitle: "Why start here",
        whyItems: [
          "Browse by scenario: first-time, long-distance, wearable, or dual stimulation",
          "Browse by experience: quietness, intensity, beginner-friendliness, or App Control",
          "Check FAQ, shipping, and returns before paying to reduce hesitation",
        ],
        links: {
          shipping: "Shipping",
          returns: "Returns",
          faq: "FAQ",
          contact: "Contact support",
        },
        featuredEyebrows: ["Best seller", "Beginner friendly", "Frequently considered"],
        featuredSectionEyebrow: "Featured",
        featuredSectionTitle: "Start with the easiest products to say yes to",
        featuredSectionCta: "View all products",
        collectionsEyebrow: "Browse by need",
        collectionsTitle: "Don’t let users stall on the homepage",
        collectionCardCta: "View this route →",
        guidanceEyebrow: "How to start",
        guidanceTitle: "Don’t get stuck in specs too early",
        guidanceSteps: [
          {
            title: "Start with your scenario",
            copy: "First-time, quieter use, wearable, or App Control. Clarifying your scenario narrows options faster than comparing specs first.",
          },
          {
            title: "Then check budget and learning curve",
            copy: "If you want an easier first purchase, prioritize ease of use, quietness, and beginner fit rather than intensity alone.",
          },
          {
            title: "Only then compare product pages",
            copy: "Once direction is clear, compare price, stock, shipping, FAQ, and support details with much less hesitation.",
          },
        ],
        audienceEyebrow: "Who this helps",
        audienceTitle: "This homepage is not built to dump products on you",
        audienceDescription:
          "The goal is to help people understand themselves first, then enter the right collection, quiz, or product page instead of bouncing between unfamiliar terms.",
        audienceBlocks: [
          "People buying for the first time and trying not to get lost",
          "People who care about quietness, discreet packaging, and lower-friction use",
          "People exploring App Control, long-distance, or wearable routes",
        ],
        audiencePrimaryCta: "Start the quiz",
        audienceSecondaryCta: "Read guides first",
        trustEyebrow: "Buy with confidence",
        trustTitle: "Make “I want this” turn into “I placed the order”",
        trustPrimaryCta: "Go to checkout",
        trustBlocks: [
          { title: "Discreet packaging", copy: "Orders use discreet packaging and private billing descriptors by default." },
          { title: "Ships within 48 hours", copy: "In-stock orders usually ship within 48 hours with tracking support." },
          { title: "Support before and after purchase", copy: "FAQ, email support, and help pages stay available before and after checkout." },
        ],
        collectionHighlights: [
          { title: "First-time picks", summary: "Start with lower-friction choices, quietness, and scenario fit." },
          { title: "Wearable and remote control", summary: "Best for long-distance, App Control, and more hands-free use." },
          { title: "Dual stimulation", summary: "Best for users seeking stronger feedback and fuller stimulation." },
        ],
      },
      guides: {
        metadataTitle: "Guides",
        metadataDescription: "Buying guides, scenario-based advice, and product handoff pages.",
        title: "Guides",
        intro: "Content hub for published guide articles from control-plane drafts or Sanity.",
        startTitle: "Start from content, then narrow to products",
        startDescription: "If you don’t know the right model yet, start from a guide. If you want to narrow faster, take the quiz or go straight to the shop.",
        primaryCta: "Find your match",
        secondaryCta: "Shop all",
        listTitle: "Articles",
        sourceLabel: "source",
        backToGuides: "Back to Guides",
        summaryTitle: "Quick takeaway",
        audienceTitle: "Who this guide is for",
        nextStepTitle: "What to do next",
        bodyTitle: "Body and rationale",
        fallbackBody1: "The full body is not available yet, but you can still use this guide to narrow your direction.",
        fallbackBody2: "If this is your first purchase, go back to the quiz first. If you already know your route, jump into the related collection or product page.",
        relatedProductsTitle: "Continue from this guide into products",
        relatedProductsDescription: "Use the narrowed-down route here to compare real product specs, FAQ, and pricing.",
        quizCta: "Take the quiz",
        collectionsTitle: "Continue by collection",
        nextStepBlockTitle: "Next step",
        nextStepBlockDescription: "If related products are not configured yet, narrow down through the quiz first and then move into product pages.",
        shopAll: "View all products",
        quickSummaryFallback:
          "This guide narrows choices by scenario, fit, and decision criteria before pushing you back into product pages.",
        audienceSummaryWithCollections: (collections: string[]) =>
          `If you are comparing ${collections.join(", ")}, this guide works well as a first narrowing step.`,
        audienceSummaryFallback:
          "If you do not know the exact product yet but know the route or scenario, this guide is a better first read.",
        nextStepSummaryWithCount: (count: number) =>
          `The fastest next step is to compare the ${count} product suggestions linked from this guide.`,
        nextStepSummaryFallback:
          "If the body doesn’t fully answer your question yet, go back to the quiz or collections to keep narrowing.",
      },
      product: {
        metadataDescriptionSuffix: "Product details, fit, and FAQ.",
        notFoundTitle: "Product not found",
        notFoundDescription: "This product may have been removed, renamed, or the link is no longer valid.",
        previewBadge: "Preview mode: unpublished content is being rendered for review only.",
        backToShop: "Back to shop",
        defaultDescription:
          "This page focuses on pricing, stock, core specs, and the buying path first so you can decide quickly whether it fits.",
        draftActive: "Draft active",
        quickCheckTitle: "30-second check",
        quickCheckBadge: "Decide first, add to cart second",
        quickCheckWithoutSubtitle: "The main advantage here is clearer decision-making and a more focused buying flow.",
        quickCheckFallbackWho:
          "If you are deciding between first-time use, discreet use, or narrowing down quickly, this page is the right starting point.",
        whatItIs: "What this is",
        whoItsFor: "Who it suits best",
        whyChooseIt: "Why choose it",
        fallbackWhatItIs: (title: string) =>
          `${title} focuses on price, stock, core specs, and the purchase path so you can make an initial decision quickly.`,
        fallbackWho:
          "People buying for the first time, trying to narrow down faster, or prioritizing quieter and lower-friction use.",
        fallbackWhoList: ["First-time buyers who want fewer missteps", "People who want a quieter or more discreet experience"],
        fallbackWhyChoose:
          "The value proposition is easier to read, the buying information is more concentrated, and the FAQ appears earlier in the flow.",
        whyWorthBuying: "Why it’s worth considering",
        whyWorthBuyingFallback: ["Easy to understand quickly", "Built for a more discreet experience", "Helps shorten the purchase decision"],
        whyDifferent: "What makes it different",
        whyDifferentFallback: ["Clearer value proposition", "Better suited for a first or lower-friction purchase"],
        whatsInBox: "What’s in the box",
        whatsInBoxFallback: ["Main device", "Charging cable", "Basic usage guide"],
        specs: "Specs",
        specsFallback: "Material / waterproofing / battery / charging / size",
        care: "Use and storage",
        careFallback: ["Clean after use", "Keep dry and store as instructed"],
        priceAndStock: "Price and availability",
        stockStatus: "Stock",
        inStock: "Available",
        outOfStock: "Out of stock",
        shippingSla: "Shipping speed",
        shippingSlaValue: "Within 48 hours",
        packaging: "Packaging",
        packagingValue: "Discreet packaging",
        addToCart: "Add to cart",
        goToCart: "Go to cart",
        checkout: "Go to checkout",
        shipping: "Shipping",
        returns: "Returns",
        contact: "Contact support",
        productFaq: "Common questions before buying",
        viewFullFaq: "View full FAQ",
        productFaqFallback1: "This product does not have a dedicated FAQ yet, but you can still make the purchase decision here.",
        productFaqFallback2: "Check the general FAQ, shipping, and returns first. If something is still unclear, contact support directly.",
        continueEyebrow: "Keep browsing",
        relatedProducts: "Related products",
        viewMore: "View more",
        heroBadgeWearable: "Wearable",
        heroBadgePrimary: "Featured pick",
        specLabels: {
          material: "Material",
          waterproof: "Waterproofing",
          runtime: "Battery",
          charge: "Charging",
          size: "Size",
          weight: "Weight",
          notWaterproof: "Not waterproof",
          minutes: "min",
        },
      },
      faq: {
        metadataDescription: "Common questions about privacy, cleaning, connectivity, shipping, and pre-purchase details.",
        previewBadge: "Preview mode: unpublished content is being rendered for review only.",
        introSanity:
          "This page concentrates the questions people ask most before checkout, including discreet packaging, cleaning, connectivity, shipping, and support.",
        introDraft:
          "Published FAQ content is shown first so people can review privacy, cleaning, shipping, and usage concerns before payment.",
        introFallback:
          "This page already covers the most common pre-purchase questions. If your question is still missing, check shipping, returns, or contact support directly.",
        cards: {
          beforeBuyTitle: "Check before buying",
          beforeBuyCopy: "Whether it fits you, whether it stays quiet, whether it supports App Control, and whether it feels beginner-friendly.",
          beforePayTitle: "Confirm before payment",
          beforePayCopy: "Shipping method, discreet packaging, return scope, and what information to prepare before contacting support.",
          unsureTitle: "If you’re still unsure",
          unsureCopy: "Take the quiz first, then return to product pages to compare FAQ, specs, and pricing.",
        },
        quickAnswersTitle: "Quick answers",
        quickAnswersDescription:
          "If you only need to confirm whether you can order now, how discreet it is, or how issues are handled, start with these three questions.",
        targetLabel: "Target",
        groupTitles: {
          global: "FAQ",
          productPrefix: "FAQ",
          guidePrefix: "Guide FAQ",
          collectionPrefix: "Collection FAQ",
        },
      },
      quiz: {
        pageTitle: "Find Your Match",
        pageDescription:
          "Answer a few questions about first-time use, wearable preference, App Control, and budget to narrow the shortlist quickly.",
        firstTimeCta: "Browse first-time picks",
        shopAllCta: "Shop all",
        disabled: "AI concierge is currently disabled. Enable it with `NEXT_PUBLIC_AI_CONCIERGE_ENABLED=true`.",
        experiment: "Experiment",
        source: "source",
        q1: "Q1. Is this your first toy?",
        q2: "Q2. Do you prefer wearable?",
        q3: "Q3. Do you want dual stimulation?",
        q4: "Q4. What’s your budget range?",
        q5: "Q5. What control style do you prefer?",
        yes: "Yes",
        no: "No",
        simpleControls: "Simple controls",
        appControl: "Prefer App Control",
        matchTitle: "Your Match",
        matchIntro: "Based on your answers, these are the 3 closest options to start from.",
        summaryTitle: "Recommendation summary",
        topPick: "Top pick",
        topPickHint: "Highest-conversion route: add the top pick first, then move into checkout.",
        processing: "Processing...",
        topPickCheckout: "Add top pick & checkout",
        goToCart: "Go to cart",
        bestNextStep: "Best next step",
        bundleRoute: "Bundle route",
        quickAdd: "Quick add",
        quickAddHint: "Stay on this page",
        addFail: "Failed to add to cart. Try from the product page.",
        addSuccess: "Added to cart.",
        reasonTags: {
          wearable: "Matches wearable preference",
          dual: "Includes dual stimulation",
          firstTime: "More suitable for first-time use",
          app: "Supports App Control",
          simple: "Simpler controls",
          advanced: "Better for advanced control",
          overall: "Strong overall fit",
          budget: (label: string) => `Matches budget ${label}`,
        },
        budgetAny: "any",
        resultSummary: {
          firstTime: "Beginner friendly",
          notFirstTime: "No beginner restriction",
          wearable: "Wearable leaning",
          nonWearable: "Non-wearable leaning",
          dual: "Dual stimulation leaning",
          nonDual: "Dual not required",
          app: "App Control leaning",
          simple: "Simple controls leaning",
          budget: (label: string) => `Budget ${label}`,
        },
        collectionTitles: {
          firstTime: "First-time picks",
          wearable: "Wearable picks",
          app: "App-controlled picks",
          dual: "Dual stimulation picks",
          curated: "Curated picks",
        },
        collectionSummaries: {
          firstTime: "A faster route for beginner-friendly and lower-friction products.",
          wearable: "Best for wearable, discreet, and hands-free use.",
          app: "Best for App Control, remote interaction, and finer-grained control.",
          dual: "Best for comparing stronger dual-stimulation routes quickly.",
          curated: "If direction is still unclear, start from this curated set.",
        },
        bundleTitles: {
          app: "App control bundle",
          wearable: "Wearable bundle",
          dual: "Dual stimulation bundle",
          starter: "Starter bundle",
        },
        bundleSummaries: {
          app: "Compares the App Control route and adjacent products in one place.",
          wearable: "A better route for browsing wearable and discreet combinations.",
          dual: "A faster way to compare different dual-stimulation paths.",
          starter: "Start from the easier bundle route before moving into more advanced control or stimulation types.",
        },
      },
    };
  }

  return {
    header: { shop: "去选购", cart: "购物车" },
    newsletter: {
      title: "订阅更新",
      description: "接收新品、导购和发货相关更新，不会高频打扰。",
      submitIdle: "订阅",
      submitPending: "提交中...",
      emptyEmail: "请输入邮箱地址。",
      submitError: "订阅失败，请稍后再试。",
      submitSuccess: (brandName: string) => `已订阅 ${brandName} 更新。`,
    },
    home: {
      heroTitle: "更会推荐、也更容易下单的私密好物商店。",
      heroDescription: "从入门推荐、场景筛选到正式下单与售后支持，把“想试试”变成真正能放心购买。",
      primaryCta: "进入商店",
      secondaryCta: "先做选购问答",
      stats: ["已上线可售商品", "常规现货发货时效", "选购与售后支持"],
      whyTitle: "为什么先从这里开始选",
      whyItems: [
        "按场景选：第一次入门、异地互动、可穿戴、双重刺激",
        "按体验选：静音度、强度、新手友好度、是否支持 App",
        "购买前先看 FAQ、配送、退换说明，减少支付前犹豫",
      ],
      links: { shipping: "配送说明", returns: "退换政策", faq: "常见问题", contact: "联系支持" },
      featuredEyebrows: ["热销推荐", "入门友好", "高讨论度"],
      featuredSectionEyebrow: "精选推荐",
      featuredSectionTitle: "先从最容易成交的商品开始",
      featuredSectionCta: "查看全部商品",
      collectionsEyebrow: "按需求进入",
      collectionsTitle: "别让用户在首页停太久",
      collectionCardCta: "去看这类商品 →",
      guidanceEyebrow: "怎么开始选",
      guidanceTitle: "别一开始就被参数拖住",
      guidanceSteps: [
        {
          title: "先看自己属于哪类场景",
          copy: "第一次购买、想要更安静低调、想要 wearable，还是更在意 App Control。先明确场景，比先看参数更容易缩小范围。",
        },
        {
          title: "再看预算和使用门槛",
          copy: "如果你希望第一次就买得轻松，优先看操作复杂度、静音度和是否适合新手，而不只是刺激强度。",
        },
        {
          title: "最后再进入商品页比较",
          copy: "当方向已经清楚，再去比较价格、库存、配送、FAQ 和售后说明，支付前的犹豫会少很多。",
        },
      ],
      audienceEyebrow: "更适合谁",
      audienceTitle: "这不是一个只会堆商品的首页",
      audienceDescription:
        "我们更希望把首页做成一个“先理解自己，再开始看货”的入口，所以会优先把用户带到适合的合集、问答和商品页。",
      audienceBlocks: [
        "第一次购买但不想在信息里迷路的人",
        "重视安静、隐私包装和更低负担体验的人",
        "想看 App Control、异地互动或 wearable 路线的人",
      ],
      audiencePrimaryCta: "直接开始问答",
      audienceSecondaryCta: "先看导购内容",
      trustEyebrow: "放心购买",
      trustTitle: "让“想买”顺利走到“下单”",
      trustPrimaryCta: "直接去结账",
      trustBlocks: [
        { title: "隐私包装", copy: "默认低调包装与私密账单描述，减少收货顾虑。" },
        { title: "48 小时内发货", copy: "常规现货订单 48 小时内发出，支持物流跟踪。" },
        { title: "售后支持", copy: "购买前后都可以从 FAQ、客服邮箱和帮助页获得支持。" },
      ],
      collectionHighlights: [
        { title: "第一次选购", summary: "从入门友好、静音度和使用场景开始，快速缩小范围。" },
        { title: "可穿戴与远程控制", summary: "适合异地互动、App 控制和更灵活的解放双手体验。" },
        { title: "双重刺激", summary: "适合想要更强反馈、更完整包裹感的用户。" },
      ],
    },
    guides: {
      metadataTitle: "Guides",
      metadataDescription: "购买指南、场景建议与关联商品入口。",
      title: "Guides",
      intro: "内容中心：优先展示已发布的 guideArticle，支持从 control-plane draft 或 Sanity 渲染。",
      startTitle: "先从内容开始，再缩小到商品",
      startDescription: "如果你还没有明确型号，先看 guide；如果想更快缩小范围，直接走问答或进入商品列表。",
      primaryCta: "Find your match",
      secondaryCta: "Shop all",
      listTitle: "文章列表",
      sourceLabel: "source",
      backToGuides: "Back to Guides",
      summaryTitle: "先看结论",
      audienceTitle: "这篇适合谁",
      nextStepTitle: "下一步做什么",
      bodyTitle: "正文与判断依据",
      fallbackBody1: "当前正文内容还没有完全补齐，但你可以先按这篇 guide 的主题继续缩小范围。",
      fallbackBody2: "如果你是第一次购买，优先回到问答页；如果你已经知道自己想看哪类路线，直接进入相关 collection 或商品页会更快。",
      relatedProductsTitle: "按这篇 guide 继续看商品",
      relatedProductsDescription: "把刚刚缩小出来的范围，直接落到真实商品的参数、FAQ 和价格上。",
      quizCta: "去做问答",
      collectionsTitle: "按 collection 继续缩小范围",
      nextStepBlockTitle: "下一步",
      nextStepBlockDescription: "还没有配置关联商品时，先通过问答缩小范围，再进入商品页。",
      shopAll: "查看全部商品",
      quickSummaryFallback: "这篇导购会围绕使用场景、选择标准和适合人群展开，先帮你缩小范围，再把判断带回商品页。",
      audienceSummaryWithCollections: (collections: string[]) =>
        `如果你正在比较 ${collections.join("、")} 这些方向，这篇更适合作为先缩小范围的入口。`,
      audienceSummaryFallback: "如果你还没有确定具体商品，但已经知道大致场景或使用路线，这篇 guide 更适合先读。",
      nextStepSummaryWithCount: (count: number) =>
        `读完后最省时间的动作，是直接对照这篇 guide 推荐的 ${count} 款商品继续看参数、FAQ 和价格。`,
      nextStepSummaryFallback: "如果正文还没完全覆盖你的问题，下一步最有效的是回到 quiz 或 collection 继续缩小范围。",
    },
    product: {
      metadataDescriptionSuffix: "商品详情、适合人群与 FAQ。",
      notFoundTitle: "没找到这款商品",
      notFoundDescription: "这款商品可能已下架、改名，或当前链接已失效。",
      previewBadge: "Preview mode: 当前页面正在渲染未发布内容（仅用于预览）。",
      backToShop: "返回商品列表",
      defaultDescription: "当前优先展示价格、库存、基础参数和购买入口，方便你先快速判断这款商品是否适合自己。",
      draftActive: "Draft active",
      quickCheckTitle: "30 秒快速判断",
      quickCheckBadge: "适合先判断，再决定要不要加购",
      quickCheckWithoutSubtitle: "的核心卖点在于决策清晰、信息集中。",
      quickCheckFallbackWho: "如果你在第一次购买、低调体验或快速缩小范围之间犹豫，这页就是先做判断的起点。",
      whatItIs: "这是什么",
      whoItsFor: "更适合谁",
      whyChooseIt: "为什么选它",
      fallbackWhatItIs: (title: string) => `${title} 当前优先展示价格、库存、参数与购买路径，帮助你快速做初步判断。`,
      fallbackWho: "第一次选购、想先缩小范围，或更在意低调体验与决策效率的人。",
      fallbackWhoList: ["第一次选购但不想踩坑", "需要更安静或更低调的体验"],
      fallbackWhyChoose: "卖点表达直接、购买信息集中、参数与 FAQ 靠前，适合快速比较后再决定是否下单。",
      whyWorthBuying: "为什么值得买",
      whyWorthBuyingFallback: ["适合快速上手", "强调低调体验", "更容易理解购买决策"],
      whyDifferent: "这款为什么不一样",
      whyDifferentFallback: ["更容易理解卖点", "更适合做首单选择"],
      whatsInBox: "包装内含",
      whatsInBoxFallback: ["主机", "充电线", "基础使用说明"],
      specs: "产品参数",
      specsFallback: "材质 / 防水 / 续航 / 充电 / 尺寸",
      care: "使用与收纳",
      careFallback: ["使用后及时清洁", "保持干燥并按说明收纳"],
      priceAndStock: "价格与库存",
      stockStatus: "库存状态",
      inStock: "可下单",
      outOfStock: "暂时缺货",
      shippingSla: "发货时效",
      shippingSlaValue: "48 小时内",
      packaging: "包装方式",
      packagingValue: "低调隐私包装",
      addToCart: "加入购物车",
      goToCart: "去购物车",
      checkout: "直接去结账",
      shipping: "配送说明",
      returns: "退换政策",
      contact: "购买前咨询",
      productFaq: "购买前常见问题",
      viewFullFaq: "查看完整 FAQ",
      productFaqFallback1: "这款商品暂时还没有单独整理 FAQ，但你仍然可以先完成购买判断。",
      productFaqFallback2: "建议先查看通用 FAQ、配送说明和退换政策；如果仍有疑问，可以直接联系支持。",
      continueEyebrow: "继续逛",
      relatedProducts: "相关商品",
      viewMore: "查看更多",
      heroBadgeWearable: "可穿戴",
      heroBadgePrimary: "主力单品",
      specLabels: {
        material: "材质",
        waterproof: "防水",
        runtime: "续航",
        charge: "充电",
        size: "尺寸",
        weight: "重量",
        notWaterproof: "不支持防水",
        minutes: "分钟",
      },
    },
    faq: {
      metadataDescription: "常见问题、隐私、清洁、连接与购买前说明。",
      previewBadge: "Preview mode: 当前页面正在渲染未发布内容（仅用于预览）。",
      introSanity: "这里集中回答购买前最常被问到的问题，包括隐私包装、清洁、连接稳定性、配送与售后说明。适合在下单前先快速确认关键信息。",
      introDraft: "这里优先展示已经发布的 FAQ 内容，方便在支付前先把隐私、清洁、配送和使用顾虑一次看清。",
      introFallback: "这里已经覆盖购买前最常见的疑问。若这里没有命中你的问题，可以继续查看配送、退换或直接联系支持。",
      cards: {
        beforeBuyTitle: "购买前先看",
        beforeBuyCopy: "是否适合自己、是否安静、是否支持 App，以及第一次购买是否容易上手。",
        beforePayTitle: "支付前再确认",
        beforePayCopy: "配送方式、隐私包装、退换范围和联系客服时需要准备哪些信息。",
        unsureTitle: "如果还不确定",
        unsureCopy: "可以先做问答缩小范围，再回到商品页比较 FAQ、参数和价格。",
      },
      quickAnswersTitle: "快速回答",
      quickAnswersDescription: "如果你现在只想先确认能不能下单、会不会太显眼、出了问题怎么处理，先看这三条最常被引用的问题。",
      targetLabel: "Target",
      groupTitles: {
        global: "FAQ",
        productPrefix: "商品 FAQ",
        guidePrefix: "Guide FAQ",
        collectionPrefix: "Collection FAQ",
      },
    },
    quiz: {
      pageTitle: "Find Your Match",
      pageDescription: "如果你不想一开始就在商品列表里反复横跳，这里会先按第一次购买、是否偏好 wearable、是否想要 App Control 和预算范围，帮你快速缩小到更接近的几款。",
      firstTimeCta: "Browse first-time picks",
      shopAllCta: "Shop all",
      disabled: "AI 导购当前未开启（`NEXT_PUBLIC_AI_CONCIERGE_ENABLED=true` 后生效）。",
      experiment: "Experiment",
      source: "source",
      q1: "Q1. Is this your first toy?",
      q2: "Q2. Prefer wearable?",
      q3: "Q3. Want dual stimulation?",
      q4: "Q4. Budget range?",
      q5: "Q5. Control preference?",
      yes: "Yes",
      no: "No",
      simpleControls: "Simple controls",
      appControl: "Prefer App Control",
      matchTitle: "Your Match",
      matchIntro: "基于你的回答，我们优先推荐下面 3 个候选。",
      summaryTitle: "推荐摘要",
      topPick: "Top pick",
      topPickHint: "更强的转化路径：先加入购物车，再直接去结账。",
      processing: "处理中...",
      topPickCheckout: "Add top pick & checkout",
      goToCart: "去购物车",
      bestNextStep: "Best next step",
      bundleRoute: "Bundle route",
      quickAdd: "Quick add",
      quickAddHint: "不会离开当前页面",
      addFail: "加购失败，请打开商品页再试。",
      addSuccess: "已加入购物车。",
      reasonTags: {
        wearable: "适合 wearable 偏好",
        dual: "包含 dual stimulation",
        firstTime: "更适合 first-time 入门",
        app: "支持 App Control",
        simple: "操作更简单",
        advanced: "偏进阶控制体验",
        overall: "整体匹配度较高",
        budget: (label: string) => `预算匹配 ${label}`,
      },
      budgetAny: "any",
      resultSummary: {
        firstTime: "入门友好",
        notFirstTime: "不限制入门难度",
        wearable: "偏 wearable",
        nonWearable: "偏非 wearable",
        dual: "偏 dual stimulation",
        nonDual: "不强求 dual",
        app: "偏 App Control",
        simple: "偏简单操作",
        budget: (label: string) => `预算 ${label}`,
      },
      collectionTitles: {
        firstTime: "First-time picks",
        wearable: "Wearable picks",
        app: "App-controlled picks",
        dual: "Dual stimulation picks",
        curated: "Curated picks",
      },
      collectionSummaries: {
        firstTime: "更适合快速缩小范围，先看入门组合与低门槛款式。",
        wearable: "优先看 wearable 路线，兼顾 discreet 和 hands-free 使用场景。",
        app: "适合想要 App Control、远程互动和更细粒度控制的人。",
        dual: "优先看 dual stimulation 路线，快速对比更强刺激组合。",
        curated: "如果还没有明确方向，先从这组精选路线开始。",
      },
      bundleTitles: {
        app: "App control bundle",
        wearable: "Wearable bundle",
        dual: "Dual stimulation bundle",
        starter: "Starter bundle",
      },
      bundleSummaries: {
        app: "把 App Control 主推荐和同路线商品放在一起，适合继续比较或一起购买。",
        wearable: "更适合 wearable / discreet 路线的组合浏览。",
        dual: "更适合想直接比较 dual 路线体验差异的人。",
        starter: "先从入门路线组合开始，再决定是否进入更进阶的控制或刺激类型。",
      },
    },
  };
}
